REMOTE_URL:
  - file:///opt/spaceone/plugin/config/database.yaml
  - file:///opt/spaceone/plugin/config/shared.yaml
  - file:///opt/spaceone/plugin/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: plugin
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: plugin_user
      password: plugin_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/plugin.log
  CONNECTORS:
    IdentityConnector:
      endpoint:
        v1: grpc://identity:50051
    SecretConnector:
      endpoint:
        v1: grpc://secret:50051
    PluginConnector:
      endpoint:
        v1: grpc://plugin:50051
    RepositoryConnector:
      endpoint:
        v1: grpc://repository:50051
